---
# you'll need to change these
nonroot_username: ec2-user
yum_server: yum.murdock.rhtps.io
docker_volume: /dev/xvdb
docker_images_path: /mnt
gitlab_rpm_path: /mnt
apps_subdomain: apps.murdock.rhtps.io
registry_ip: 172.16.0.1

# you might need to change these
rhel_directory: rhel-7-server-rpms
extras_directory: rhel-7-server-extras-rpms
ose33_directory: rhel-7-server-ose-3.3-rpms
docker_images_tarball: ose33_images.tar.gz
gitlab_username: murdock
tarball_untar_dir: /root